// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gknxraguamuowtpivswy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrbnhyYWd1YW11b3d0cGl2c3d5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3NTg5MzMsImV4cCI6MjA1MzMzNDkzM30.y9pHIOXNzd-HjWfQUswNcEbwFbZcoMA9SNAnn8ODt2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);